server:
  servlet:
    context-path: /tourism
  port: 9080
tourism:
  service:
    name: TOURISM
logging:
  level:
    com.tourism: DEBUG
    org.hibernate.SQL: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tourism
    username: root
    password: Villa#25
