server:
  servlet:
    context-path: /tourism
  port: 9080
tourism:
  service:
    name: TOURISM
logging:
  level:
    com.tourism: DEBUG
    org.hibernate.SQL: DEBUG
spring:
  jpa:
    properties:
      hibernate.dialect : org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgres://ec2-54-83-1-101.compute-1.amazonaws.com:5432/d4b57jg6msou3a
    username: bkwxsyvgvneiwr
    password: a571ae8e7313473f485711b7111709071e524137c9d99761b987f4ebdb957b6f 
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/tourism
#    username: root
#    password: Villa#25
    
#    /heroku_ef87f5e491f608a?reconnect=true??
#spring:
#  datasource:
#    url: mysql://:us-cdbr-iron-east-02.cleardb.net/heroku_ef87f5e491f608a
#    username: b92721fe7676ea
#    password: 13ddb0dd   "target": "https://kiel-tourism-server.herokuapp.com/",

#  "target": "https://kiel-tourism-server.herokuapp.com/",

#mysql://b92721fe7676ea:13ddb0dd@us-cdbr-iron-east-02.cleardb.net/heroku_ef87f5e491f608a?reconnect=true
#postgres://bkwxsyvgvneiwr:a571ae8e7313473f485711b7111709071e524137c9d99761b987f4ebdb957b6f@ec2-54-83-1-101.compute-1.amazonaws.com:5432/d4b57jg6msou3a

