server:
  servlet:
    context-path: /tourism
  port: 8080
tourism:
  service:
    name: TOURISM
logging:
  level:
    com.tourism: DEBUG
spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/tourism
    username: root
    password: Villa#25